# Site
name: Sagar Shah
description: Personal website
meta_description: Personal website for Sagar Shah
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
paginate: 6
baseurl:
email: 'hello@Sagar.doe'
google_analytics:
disqus:
sharethis:

# Authors
authors:
  Sagar:
    name: Sagar
    display_name: Sagar Shah
    image: /assets/images/Sagar.jpg
    email: hello@Sagar.doe
    web: example.com
    twitter:
    description: Hi, I am Sagar Shah.

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: 'category/:name/'

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: Sagar
  card: summary

facebook:
  app_id:
  publisher: Sagar.com
  admins:

social:
name: Sagar Shah
links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://www.linkedin.com/
    - https://github.com/
