# Site
title: cdrsagar
tagline: Personal website for Sagar Shah | Technical Blogs | Demonstrate programming skills
name: Sagar Shah
description: Personal website for Sagar Shah. Technical Blogs specially on Ruby on Rails, Next js, faunadb. Demonstrates my own personal projects as well.
meta_description: Personal website for Sagar Shah
logo: /assets/images/logo.png
favicon: /assets/images/logo.png
paginate: 6
baseurl:
email: 'xoqqlwln'
google_analytics:
disqus:
sharethis:

# Authors
authors:
  sagar_shah:
    name: sagar_shah
    display_name: Sagar Shah
    image: /assets/images/sagar.jpg
    email: 070bct535@ioe.edu.np
    web: cdrsagar.com
    twitter:
    description: Hi, I am Sagar Shah.

# Plugins
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-seo-tag

permalinks: pretty

# Other
markdown: kramdown
highlighter: rouge

# SEO
twitter:
  username: SagarSh17975723
  card: summary

facebook:
  app_id:
  publisher: Sagar.com
  admins:

social:
name: Sagar Shah
links:
    - https://twitter.com/
    - https://www.facebook.com/
    - https://www.linkedin.com/
    - https://github.com/
